ARG NODE_VERSION=20

FROM node:${NODE_VERSION}-slim as base

ARG PORT=3000

WORKDIR /app

COPY package.json .

RUN npm install

COPY . .

RUN npm run build

ENV NODE_ENV=production

ENV NUXT_PUBLIC_SITE_URL=${SITE_URL}
ENV NUXT_PUBLIC_SITE_NAME=${SITE_NAME}
ENV NUXT_PUBLIC_API_BASE=${API_BASE}
ENV NUXT_PUBLIC_ICON_LETTER=${ICON_LETTER}
ENV NUXT_PUBLIC_OWNER_NAME=${OWNER_NAME}
ENV NUXT_PUBLIC_OWNER_LAST_NAME=${OWNER_LAST_NAME}

EXPOSE $PORT

CMD [ "node", ".output/server/index.mjs" ]